// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0aU1yjWPj-ktm6HaOYat5_nVu2Kq6k4s',
    appId: '1:1066615764983:web:0b3acc7459aa100203a0f2',
    messagingSenderId: '1066615764983',
    projectId: 'agrimatrix-project',
    authDomain: 'agrimatrix-project.firebaseapp.com',
    storageBucket: 'agrimatrix-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfJBFW9vRXhB6P0c5HXef2xLWmW_pdCns',
    appId: '1:1066615764983:android:9e5ce2c7aee05d9803a0f2',
    messagingSenderId: '1066615764983',
    projectId: 'agrimatrix-project',
    storageBucket: 'agrimatrix-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGtGitBzxDl_qvnLk43StUCFPzvWFEteE',
    appId: '1:1066615764983:ios:663b2c2a4ed9d2cb03a0f2',
    messagingSenderId: '1066615764983',
    projectId: 'agrimatrix-project',
    storageBucket: 'agrimatrix-project.firebasestorage.app',
    iosBundleId: 'com.example.agrimatrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGtGitBzxDl_qvnLk43StUCFPzvWFEteE',
    appId: '1:1066615764983:ios:663b2c2a4ed9d2cb03a0f2',
    messagingSenderId: '1066615764983',
    projectId: 'agrimatrix-project',
    storageBucket: 'agrimatrix-project.firebasestorage.app',
    iosBundleId: 'com.example.agrimatrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0aU1yjWPj-ktm6HaOYat5_nVu2Kq6k4s',
    appId: '1:1066615764983:web:0d283a7ce73641c103a0f2',
    messagingSenderId: '1066615764983',
    projectId: 'agrimatrix-project',
    authDomain: 'agrimatrix-project.firebaseapp.com',
    storageBucket: 'agrimatrix-project.firebasestorage.app',
  );
}
